### ISSUE TITLE
Order in all previous episodes on fireside and youtube

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/citizenweb3#216]
- [x] links
- [x] logos
- [x] unified format
- [x] thumbnails

**Comment by CitizenWeb3Squire** [comment]
Good morning, Serj

I am almost finished with this task. 

The cover art from Lido onward for quite a few episodes had unique art that corresponded to their NFT's. Would you like me to change those to the new Citizen Web3 cover art as well? I will finish the remaining parts of the task and if you confirm it won't take long then to change the cover art.

**Comment by CitizenWeb3Squire** [comment]
Fireside done, now starting yourtube.
